//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUICKIFYRepository
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Equipo
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Error: Debe ingresar Usuario")]
        public int Usuario_Id { get; set; }
        [Required(ErrorMessage = "Error: Debe ingresar es Admin")]
        public int isAdmin { get; set; }
        [Required(ErrorMessage = "Error: Debe ingresar Proyecto")]
        public int Proyecto_Id { get; set; }
    
        public virtual Proyecto Proyecto { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
