//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUICKIFYRepository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SI657_Entities : DbContext
    {
        private static SI657_Entities instance = null;

        private SI657_Entities()
            : base("name=SI657_Entities")
        {
        }

        public static SI657_Entities getInstance() {
            if (instance == null) {
                instance = new SI657_Entities();
            }
            return instance;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cargo> Cargo { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Equipo> Equipo { get; set; }
        public virtual DbSet<HistoriaUsuario> HistoriaUsuario { get; set; }
        public virtual DbSet<Proyecto> Proyecto { get; set; }
        public virtual DbSet<Tarea> Tarea { get; set; }
    }
}
